phrase:
  project_id: 

  push:
    sources:
      - file: ./res/values/strings.xml
        params:
          file_format: xml
          locale_id: en
      - file: ./res/values-de/strings.xml
        params:
          file_format: xml
          locale_id: de
      - file: ./res/values-es/strings.xml
        params:
          file_format: xml
          locale_id: es
      - file: ./res/values-fr/strings.xml
        params:
          file_format: xml
          locale_id: fr

  pull:
    targets:
      - file: ./res/values/strings.xml
        params:
          file_format: xml
          locale_id: en
      - file: ./res/values-de/strings.xml
        params:
          file_format: xml
          locale_id: de
      - file: ./res/values-es/strings.xml
        params:
            file_format: xml
            locale_id: es
      - file: ./res/values-fr/strings.xml
        params:
          file_format: xml
          locale_id: fr